require 'rails_helper'
# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe 'Posts', type: :request do
  describe 'GET /index' do
    it 'returns http success' do
      get '/users/:user_id/posts'
      expect(response).to have_http_status(:success)
    end
  end
  describe 'GET /index' do
    it 'returns a placeholder in the index file' do
      get '/users/:user_id/posts'
      expect(response.body).to include('list')
    end
  end
  describe 'GET /show' do
    it 'return http success' do
      get '/users/:user_id/posts/show'
      expect(response).to have_http_status(:success)
      expect(response.body).to include('Post made by')
    end
  end
end
